-- Seed default subscription plans (idempotent)
INSERT INTO plan (id, slug, name, price_monthly, price_yearly, max_users, max_stores, max_products,
                  max_sales_per_month, max_clients, max_suppliers, feature_expenses, feature_reports,
                  feature_advanced_reports, feature_multi_payment, feature_export_pdf, feature_export_excel,
                  feature_client_credits, feature_supplier_tracking, feature_role_management, feature_api,
                  feature_custom_branding, feature_priority_support, feature_account_manager, is_active)
SELECT gen_random_uuid(),
       'starter',
       'Starter',
       5000,
       50000,
       2,
       1,
       100,
       500,
       50,
       10,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       false,
       true WHERE NOT EXISTS (SELECT 1 FROM plan WHERE slug = 'starter');

INSERT INTO plan (id, slug, name, price_monthly, price_yearly, max_users, max_stores, max_products,
                  max_sales_per_month, max_clients, max_suppliers, feature_expenses, feature_reports,
                  feature_advanced_reports, feature_multi_payment, feature_export_pdf, feature_export_excel,
                  feature_client_credits, feature_supplier_tracking, feature_role_management, feature_api,
                  feature_custom_branding, feature_priority_support, feature_account_manager, is_active)
SELECT gen_random_uuid(),
       'pro',
       'Pro',
       15000,
       150000,
       5,
       3,
       500,
       2000,
       200,
       50,
       true,
       true,
       false,
       true,
       true,
       true,
       true,
       true,
       false,
       false,
       false,
       false,
       false,
       true WHERE NOT EXISTS (SELECT 1 FROM plan WHERE slug = 'pro');

INSERT INTO plan (id, slug, name, price_monthly, price_yearly, max_users, max_stores, max_products,
                  max_sales_per_month, max_clients, max_suppliers, feature_expenses, feature_reports,
                  feature_advanced_reports, feature_multi_payment, feature_export_pdf, feature_export_excel,
                  feature_client_credits, feature_supplier_tracking, feature_role_management, feature_api,
                  feature_custom_branding, feature_priority_support, feature_account_manager, is_active)
SELECT gen_random_uuid(),
       'business',
       'Business',
       35000,
       350000,
       0,
       0,
       0,
       0,
       0,
       0,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true,
       true WHERE NOT EXISTS (SELECT 1 FROM plan WHERE slug = 'business');